name: Setup

runs:
  using: composite
  steps:
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 18.16.0
        cache: yarn
    - name: Install
      run: yarn --immutable
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
