name: Setup

inputs:
  working-directory:
    description: 'Working directory to run in, default .'
    required: false
    default: .
    type: string

runs:
  using: composite
  steps:
    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: 18.16.0
    - name: Install yarn
      run: npm install -g yarn
      shell: bash
      if: ${{ env.ACT }}
    - name: Cache
      uses: actions/cache@v4
      id: cache
      with:
        path: ${{ format('{0}/**/node_modules', inputs.working-directory) }}
        key: yarn-v1-${{ runner.os }}-${{ hashFiles(format('{0}/.nvmrc', inputs.working-directory)) }}-${{ hashFiles(format('{0}/**/yarn.lock', inputs.working-directory)) }}
    - name: Install
      working-directory: ${{ inputs.working-directory }}
      run: yarn --immutable
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
