name: Setup

inputs:
  edge:
    description: 'Whether this is an edge build (vs release)'
    required: true
    type: boolean

runs:
  using: composite
  steps:
    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: 18.16.0
    - name: Install yarn
      run: npm install -g yarn
      shell: bash
      if: ${{ env.ACT }}
    - name: Cache
      uses: actions/cache@v4
      id: cache
      with:
        path: '**/node_modules'
        key: yarn-v1-${{ runner.os }}-${{ hashFiles('.nvmrc') }}-${{ hashFiles('**/yarn.lock') }}
    - name: Install
      run: yarn --immutable
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Update translations
      run: git submodule update --remote
      shell: bash
      if: ${{ inputs.edge }}
