issue_enrichment:
  auto_enrich:
    enabled: false
reviews:
  request_changes_workflow: true
  review_status: true
  high_level_summary: false
  finishing_touches:
    docstrings:
      enabled: false
  pre_merge_checks:
    docstrings:
      enabled: false
    custom_checks:
      - mode: error
        name: 'settings'
        instructions: 'Every addition of a new setting toggle must be thoroughly evaluated against the core design principles of Actual. The settings screen is reserved for essential and foundational options only — do not introduce settings for minor UI adjustments such as sizes, paddings, colors, or margins. Prioritize preserving a simple and uncluttered user experience. Users proposing new settings must confirm in a reply to the Coderabbit comment that they have reviewed and ensured alignment with these principles. Excessive or granular UI options increase code complexity and risk confusing users, and are generally not permitted.'
      - mode: error
        name: 'linting'
        instructions: 'Do not allow any oxlint-disable lines.'
      - mode: error
        name: 'typecheck'
        instructions: 'Do not allow creating new components or utilities with the @ts-strict-ignore comment.'
  labeling_instructions:
    - label: 'suspect ai generated'
      instructions: 'This issue or PR is suspected to be generated by AI.'
    - label: 'API'
      instructions: 'This issue or PR updates the API in `packages/api`.'
    - label: 'documentation'
      instructions: 'This issue updates the documentation in `packages/docs`.'
    - label: 'contains DB migrations'
      instructions: 'This issue or PR contains DB migrations in `packages/loot-core/migrations`.'
    - label: 'size small'
      instructions: 'This issue or PR is a small change (less than 50 lines of code) that is expected to have a small impact on the codebase.'
  auto_apply_labels: true
