FROM node:20-bullseye

WORKDIR /app

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn

RUN corepack enable && corepack prepare yarn@4.10.3 --activate

EXPOSE 5006 5007 3001

CMD ["bash"]
