import type { IRuleOptions } from '@rschedule/core';
export declare function getStatus(nextDate: string, completed: boolean, hasTrans: boolean): "completed" | "paid" | "due" | "upcoming" | "missed" | "scheduled";
export declare function getHasTransactionsQuery(schedules: any): import("./query").Query;
export declare function getRecurringDescription(config: any, dateFormat: any): string;
export declare function recurConfigToRSchedule(config: any): IRuleOptions[] | ({
    byDayOfMonth: any;
    start: import("@rschedule/core").DateInput;
    end?: import("@rschedule/core").DateInput;
    duration?: number;
    count?: number;
    frequency: import("@rschedule/core").RuleOption.Frequency;
    interval?: number;
    weekStart?: import("@rschedule/core").DateAdapter.Weekday;
    byDayOfWeek?: import("@rschedule/core").RuleOption.ByDayOfWeek[];
    byHourOfDay?: import("@rschedule/core").DateAdapter.Hour[];
    byMillisecondOfSecond?: number[];
    byMinuteOfHour?: import("@rschedule/core").DateAdapter.Minute[];
    byMonthOfYear?: import("@rschedule/core").DateAdapter.Month[];
    bySecondOfMinute?: import("@rschedule/core").DateAdapter.Minute[];
} | {
    byDayOfWeek: any;
    start: import("@rschedule/core").DateInput;
    end?: import("@rschedule/core").DateInput;
    duration?: number;
    count?: number;
    frequency: import("@rschedule/core").RuleOption.Frequency;
    interval?: number;
    weekStart?: import("@rschedule/core").DateAdapter.Weekday;
    byDayOfMonth?: import("@rschedule/core").RuleOption.ByDayOfMonth[];
    byHourOfDay?: import("@rschedule/core").DateAdapter.Hour[];
    byMillisecondOfSecond?: number[];
    byMinuteOfHour?: import("@rschedule/core").DateAdapter.Minute[];
    byMonthOfYear?: import("@rschedule/core").DateAdapter.Month[];
    bySecondOfMinute?: import("@rschedule/core").DateAdapter.Minute[];
})[];
export declare function extractScheduleConds(conditions: any): {
    payee: any;
    account: any;
    amount: any;
    date: any;
};
export declare function getScheduledAmount(amount: any): any;
export declare function describeSchedule(schedule: any, payee: any): string;
