blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://discord.gg/pRYNYr4W5A
    about: Need help with something? Perhaps having issues setting up bank-sync with GoCardless or SimpleFin? Reach out to the community on Discord.
