import { Spreadsheet } from './spreadsheet/spreadsheet';
export declare function get(): Spreadsheet;
export declare function loadSpreadsheet(db: any, onSheetChange?: any): Promise<Spreadsheet>;
export declare function unloadSpreadsheet(): void;
export declare function reloadSpreadsheet(db: any): Promise<Spreadsheet>;
export declare function loadUserBudgets(db: any): Promise<void>;
export declare function getCell(sheet: string, name: string): import("./spreadsheet/spreadsheet").Node;
export declare function getCellValue(sheet: string, name: string): string | number | boolean;
export declare function startTransaction(): void;
export declare function endTransaction(): void;
export declare function waitOnSpreadsheet(): Promise<void>;
