import { ThemeDefinition } from '../../../../plugins-shared/src';
import * as colorPalette from '../palette';

export const theme: ThemeDefinition = {
    pageBackground: colorPalette.gray900,
    pageBackgroundModalActive: colorPalette.gray800,
    pageBackgroundTopLeft: colorPalette.navy800,
    pageBackgroundBottomRight: colorPalette.gray700,
    pageBackgroundLineTop: colorPalette.purple400,
    pageBackgroundLineMid: colorPalette.navy900,
    pageBackgroundLineBottom: colorPalette.navy150,
    pageText: colorPalette.navy150,
    pageTextLight: colorPalette.navy300,
    pageTextSubdued: colorPalette.navy500,
    pageTextDark: colorPalette.navy100,
    pageTextPositive: colorPalette.purple200,
    pageTextLink: colorPalette.purple400,
    pageTextLinkLight: colorPalette.purple200,

    cardBackground: colorPalette.gray800,
    cardBorder: colorPalette.purple400,
    cardShadow: colorPalette.navy700,

    tableBackground: colorPalette.navy800,
    tableRowBackgroundHover: colorPalette.navy700,
    tableText: colorPalette.navy150,
    tableTextLight: colorPalette.navy150,
    tableTextSubdued: colorPalette.navy500,
    tableTextSelected: colorPalette.navy150,
    tableTextHover: colorPalette.navy400,
    tableTextInactive: colorPalette.navy500,
    tableHeaderText: colorPalette.navy300,
    tableHeaderBackground: colorPalette.navy700,
    tableBorder: colorPalette.navy600,
    tableBorderSelected: colorPalette.purple400,
    tableBorderHover: colorPalette.purple300,
    tableBorderSeparator: colorPalette.navy400,
    tableRowBackgroundHighlight: colorPalette.purple800,
    tableRowBackgroundHighlightText: colorPalette.navy150,
    tableRowHeaderBackground: colorPalette.navy700,
    tableRowHeaderText: colorPalette.navy150,

    sidebarBackground: colorPalette.navy900,
    sidebarItemBackgroundPending: colorPalette.orange200,
    sidebarItemBackgroundPositive: colorPalette.green500,
    sidebarItemBackgroundFailed: colorPalette.red300,
    sidebarItemAccentSelected: colorPalette.purple200,
    sidebarItemBackgroundHover: colorPalette.navy700,
    sidebarItemText: colorPalette.navy150,
    sidebarItemTextSelected: colorPalette.purple200,

    menuBackground: colorPalette.navy800,
    menuItemBackground: colorPalette.navy800,
    menuItemBackgroundHover: colorPalette.navy500,
    menuItemText: colorPalette.navy100,
    menuItemTextHover: colorPalette.navy50,
    menuItemTextSelected: colorPalette.purple400,
    menuItemTextHeader: colorPalette.purple200,
    menuBorder: colorPalette.navy900,
    menuBorderHover: colorPalette.purple400,
    menuKeybindingText: colorPalette.purple200,
    menuAutoCompleteBackground: colorPalette.navy900,
    menuAutoCompleteBackgroundHover: colorPalette.navy600,
    menuAutoCompleteText: colorPalette.navy200,
    menuAutoCompleteTextHeader: colorPalette.purple200,
    menuAutoCompleteItemText: colorPalette.navy100,

    modalBackground: colorPalette.gray800,
    modalBorder: colorPalette.navy600,
    mobileHeaderBackground: colorPalette.purple800,
    mobileHeaderText: colorPalette.navy150,
    mobileHeaderTextSubdued: colorPalette.gray200,
    mobileHeaderTextHover: 'rgba(200, 200, 200, .15)',
    mobilePageBackground: colorPalette.navy700,
    mobileNavBackground: colorPalette.navy800,
    mobileNavItem: colorPalette.navy150,
    mobileNavItemSelected: colorPalette.purple400,
    mobileAccountShadow: colorPalette.navy700,
    mobileAccountText: colorPalette.blue800,
    mobileTransactionSelected: colorPalette.purple400,

    mobileViewTheme: colorPalette.purple800,
    mobileConfigServerViewTheme: colorPalette.purple500,

    markdownNormal: colorPalette.purple700,
    markdownDark: colorPalette.purple500,
    markdownLight: colorPalette.purple800,

    buttonMenuText: colorPalette.navy200,
    buttonMenuTextHover: colorPalette.navy200,
    buttonMenuBackground: 'transparent',
    buttonMenuBackgroundHover: 'rgba(200, 200, 200, .25)',
    buttonMenuBorder: colorPalette.navy500,
    buttonMenuSelectedText: colorPalette.green800,
    buttonMenuSelectedTextHover: colorPalette.orange800,
    buttonMenuSelectedBackground: colorPalette.orange200,
    buttonMenuSelectedBackgroundHover: colorPalette.orange300,
    buttonMenuSelectedBorder: colorPalette.orange200,

    buttonPrimaryText: colorPalette.white,
    buttonPrimaryTextHover: colorPalette.white,
    buttonPrimaryBackground: colorPalette.purple400,
    buttonPrimaryBackgroundHover: colorPalette.purple600,
    buttonPrimaryBorder: colorPalette.purple400,
    buttonPrimaryShadow: 'rgba(0, 0, 0, 0.6)',
    buttonPrimaryDisabledText: colorPalette.navy700,
    buttonPrimaryDisabledBackground: colorPalette.navy400,

    buttonNormalText: colorPalette.navy150,
    buttonNormalTextHover: colorPalette.navy150,
    buttonNormalBackground: colorPalette.navy800,
    buttonNormalBackgroundHover: colorPalette.navy600,
    buttonNormalBorder: colorPalette.navy300,
    buttonNormalShadow: 'rgba(0, 0, 0, 0.4)',
    buttonNormalDisabledText: colorPalette.navy500,
    buttonNormalDisabledBackground: colorPalette.navy800,
    buttonNormalDisabledBorder: colorPalette.navy500,

    calendarText: colorPalette.navy50,
    calendarBackground: colorPalette.navy900,
    calendarItemText: colorPalette.navy150,
    calendarItemBackground: colorPalette.navy800,
    calendarSelectedBackground: colorPalette.purple600,

    noticeBackground: colorPalette.green800,
    noticeText: colorPalette.green300,
    warningBackground: colorPalette.orange800,
    warningText: colorPalette.orange300,
    errorBackground: colorPalette.red800,
    errorText: colorPalette.red200,

    floatingActionBarBackground: colorPalette.purple800,
    floatingActionBarText: colorPalette.navy150,

    tooltipText: colorPalette.navy100,
    tooltipBackground: colorPalette.navy800,
    tooltipBorder: colorPalette.navy700,
};
