import { ThemeDefinition } from 'plugins-shared';
import * as colorPalette from '../palette';

export const theme: ThemeDefinition = {
    pageBackground: colorPalette.navy100,
    pageBackgroundModalActive: colorPalette.navy200,
    pageBackgroundTopLeft: colorPalette.navy100,
    pageBackgroundBottomRight: colorPalette.blue150,
    pageBackgroundLineTop: colorPalette.white,
    pageBackgroundLineMid: colorPalette.navy100,
    pageBackgroundLineBottom: colorPalette.blue150,
    pageText: '#272630',
    pageTextLight: colorPalette.navy500,
    pageTextSubdued: colorPalette.navy300,
    pageTextDark: colorPalette.navy800,
    pageTextPositive: colorPalette.purple600,
    pageTextLink: colorPalette.blue600,
    pageTextLinkLight: colorPalette.blue300,

    cardBackground: colorPalette.white,
    cardBorder: colorPalette.purple700,
    cardShadow: colorPalette.navy700,

    tableBackground: colorPalette.white,
    tableRowBackgroundHover: colorPalette.navy50,
    tableText: '#272630',
    tableTextLight: colorPalette.navy400,
    tableTextSubdued: colorPalette.navy100,
    tableTextSelected: colorPalette.navy700,
    tableTextHover: colorPalette.navy900,
    tableTextInactive: colorPalette.navy500,
    tableHeaderText: colorPalette.navy600,
    tableHeaderBackground: colorPalette.white,
    tableBorder: colorPalette.navy100,
    tableBorderSelected: colorPalette.purple500,
    tableBorderHover: colorPalette.purple400,
    tableBorderSeparator: colorPalette.navy400,
    tableRowBackgroundHighlight: colorPalette.blue150,
    tableRowBackgroundHighlightText: colorPalette.navy700,
    tableRowHeaderBackground: colorPalette.navy50,
    tableRowHeaderText: colorPalette.navy800,

    sidebarBackground: colorPalette.navy900,
    sidebarItemBackgroundPending: colorPalette.orange200,
    sidebarItemBackgroundPositive: colorPalette.green500,
    sidebarItemBackgroundFailed: colorPalette.red300,
    sidebarItemAccentSelected: colorPalette.purple200,
    sidebarItemBackgroundHover: colorPalette.navy800,
    sidebarItemText: colorPalette.navy150,
    sidebarItemTextSelected: colorPalette.purple200,

    menuBackground: colorPalette.white,
    menuItemBackground: colorPalette.navy50,
    menuItemBackgroundHover: colorPalette.navy100,
    menuItemText: colorPalette.navy900,
    menuItemTextHover: colorPalette.navy900,
    menuItemTextSelected: colorPalette.purple300,
    menuItemTextHeader: colorPalette.navy400,
    menuBorder: colorPalette.navy100,
    menuBorderHover: colorPalette.purple100,
    menuKeybindingText: colorPalette.navy400,
    menuAutoCompleteBackground: colorPalette.navy900,
    menuAutoCompleteBackgroundHover: colorPalette.navy600,
    menuAutoCompleteText: colorPalette.white,
    menuAutoCompleteTextHover: colorPalette.green150,
    menuAutoCompleteTextHeader: colorPalette.orange150,
    menuAutoCompleteItemTextHover: colorPalette.white,
    menuAutoCompleteItemText: colorPalette.white,

    modalBackground: colorPalette.white,
    modalBorder: colorPalette.white,

    mobileHeaderBackground: colorPalette.purple400,
    mobileHeaderText: colorPalette.navy50,
    mobileHeaderTextSubdued: colorPalette.gray200,
    mobileHeaderTextHover: 'rgba(200, 200, 200, .15)',
    mobilePageBackground: colorPalette.navy50,
    mobileNavBackground: colorPalette.white,
    mobileNavItem: colorPalette.gray300,
    mobileNavItemSelected: colorPalette.purple500,
    mobileAccountShadow: colorPalette.navy300,
    mobileAccountText: colorPalette.blue800,
    mobileTransactionSelected: colorPalette.purple500,

    mobileViewTheme: colorPalette.purple400,
    mobileConfigServerViewTheme: colorPalette.purple500,

    markdownNormal: colorPalette.purple150,
    markdownDark: colorPalette.purple400,
    markdownLight: colorPalette.purple100,

    buttonMenuText: colorPalette.navy100,
    buttonMenuTextHover: colorPalette.navy50,
    buttonMenuBackground: 'transparent',
    buttonMenuBackgroundHover: 'rgba(200, 200, 200, .25)',
    buttonMenuBorder: colorPalette.navy500,
    buttonMenuSelectedText: colorPalette.green800,
    buttonMenuSelectedTextHover: colorPalette.orange800,
    buttonMenuSelectedBackground: colorPalette.orange200,
    buttonMenuSelectedBackgroundHover: colorPalette.orange300,
    buttonMenuSelectedBorder: colorPalette.orange200,

    buttonPrimaryText: colorPalette.white,
    buttonPrimaryTextHover: 'inherited',
    buttonPrimaryBackground: colorPalette.purple500,
    buttonPrimaryBackgroundHover: colorPalette.purple300,
    buttonPrimaryBorder: colorPalette.purple500,
    buttonPrimaryShadow: 'rgba(0, 0, 0, 0.3)',
    buttonPrimaryDisabledText: colorPalette.white,
    buttonPrimaryDisabledBackground: colorPalette.navy300,
    buttonPrimaryDisabledBorder: 'inherited',

    buttonNormalText: colorPalette.navy900,
    buttonNormalTextHover: 'inherited',
    buttonNormalBackground: colorPalette.white,
    buttonNormalBackgroundHover: 'inherited',
    buttonNormalBorder: colorPalette.navy150,
    buttonNormalShadow: 'rgba(0, 0, 0, 0.2)',
    buttonNormalSelectedText: 'inherited',
    buttonNormalSelectedBackground: 'inherited',
    buttonNormalDisabledText: colorPalette.navy300,
    buttonNormalDisabledBackground: colorPalette.white,
    buttonNormalDisabledBorder: 'inherited',

    buttonBareText: 'inherited',
    buttonBareTextHover: 'inherited',
    buttonBareBackground: 'inherited',
    buttonBareBackgroundHover: 'inherited',
    buttonBareBackgroundActive: 'inherited',
    buttonBareDisabledText: 'inherited',
    buttonBareDisabledBackground: 'inherited',

    calendarText: colorPalette.navy50,
    calendarBackground: colorPalette.navy900,
    calendarItemText: colorPalette.navy150,
    calendarItemBackground: colorPalette.navy800,
    calendarSelectedBackground: colorPalette.navy500,

    noticeBackground: colorPalette.green150,
    noticeBackgroundLight: 'inherited',
    noticeBackgroundDark: 'inherited',
    noticeText: colorPalette.green700,
    noticeTextLight: 'inherited',
    noticeTextDark: 'inherited',
    noticeTextMenu: 'inherited',
    noticeTextMenuHover: 'inherited',
    noticeBorder: 'inherited',

    warningBackground: colorPalette.orange200,
    warningText: colorPalette.orange700,
    warningTextLight: 'inherited',
    warningTextDark: 'inherited',
    warningBorder: 'inherited',

    errorBackground: colorPalette.red100,
    errorText: colorPalette.red500,
    errorTextDark: 'inherited',
    errorTextDarker: 'inherited',
    errorTextMenu: 'inherited',
    errorBorder: 'inherited',

    upcomingBackground: colorPalette.purple100,
    upcomingText: colorPalette.purple700,
    upcomingBorder: 'inherited',

    formLabelText: 'inherited',
    formLabelBackground: 'inherited',
    formInputBackground: 'inherited',
    formInputBackgroundSelected: 'inherited',
    formInputBackgroundSelection: 'inherited',
    formInputBorder: 'inherited',
    formInputTextReadOnlySelection: 'inherited',
    formInputBorderSelected: 'inherited',
    formInputText: 'inherited',
    formInputTextSelected: 'inherited',
    formInputTextPlaceholder: 'inherited',
    formInputTextPlaceholderSelected: 'inherited',
    formInputTextSelection: 'inherited',
    formInputShadowSelected: 'inherited',
    formInputTextHighlight: 'inherited',

    checkboxText: 'inherited',
    checkboxBackgroundSelected: 'inherited',
    checkboxBorderSelected: 'inherited',
    checkboxShadowSelected: 'inherited',
    checkboxToggleBackground: 'inherited',
    checkboxToggleBackgroundSelected: 'inherited',
    checkboxToggleDisabled: 'inherited',

    pillBackground: 'inherited',
    pillBackgroundLight: 'inherited',
    pillText: 'inherited',
    pillTextHighlighted: 'inherited',
    pillBorder: 'inherited',
    pillBorderDark: 'inherited',
    pillBackgroundSelected: 'inherited',
    pillTextSelected: 'inherited',
    pillBorderSelected: 'inherited',
    pillTextSubdued: 'inherited',

    reportsRed: 'inherited',
    reportsBlue: 'inherited',
    reportsGreen: 'inherited',
    reportsGray: 'inherited',
    reportsLabel: 'inherited',
    reportsInnerLabel: 'inherited',

    noteTagBackground: 'inherited',
    noteTagBackgroundHover: 'inherited',
    noteTagText: 'inherited',

    budgetOtherMonth: 'inherited',
    budgetCurrentMonth: 'inherited',
    budgetHeaderOtherMonth: 'inherited',
    budgetHeaderCurrentMonth: 'inherited',

    floatingActionBarBackground: colorPalette.purple400,
    floatingActionBarBorder: 'inherited',
    floatingActionBarText: colorPalette.navy50,

    tooltipText: colorPalette.navy900,
    tooltipBackground: colorPalette.white,
    tooltipBorder: colorPalette.navy150,
};;
