import { ThemeDefinition } from 'plugins-shared';
import * as colorPalette from '../palette';

export const theme: ThemeDefinition = {
    pageBackground: colorPalette.gray600,
    pageBackgroundModalActive: colorPalette.gray700,
    pageBackgroundTopLeft: colorPalette.gray800,
    pageBackgroundBottomRight: colorPalette.gray700,
    pageBackgroundLineTop: colorPalette.purple300,
    pageBackgroundLineMid: colorPalette.gray900,
    pageBackgroundLineBottom: colorPalette.gray150,
    pageText: colorPalette.gray100,
    pageTextLight: colorPalette.gray200,
    pageTextSubdued: colorPalette.gray400,
    pageTextDark: colorPalette.gray100,
    pageTextPositive: colorPalette.purple200,
    pageTextLink: colorPalette.purple300,
    pageTextLinkLight: colorPalette.purple300,

    cardBackground: colorPalette.gray800,
    cardBorder: colorPalette.purple300,
    cardShadow: colorPalette.gray900,

    tableBackground: colorPalette.gray800,
    tableRowBackgroundHover: colorPalette.gray500,
    tableText: colorPalette.gray150,
    tableTextLight: colorPalette.gray150,
    tableTextSubdued: colorPalette.gray500,
    tableTextSelected: colorPalette.gray800,
    tableTextHover: colorPalette.gray400,
    tableTextInactive: colorPalette.gray400,
    tableHeaderText: colorPalette.gray200,
    tableHeaderBackground: colorPalette.gray900,
    tableBorder: colorPalette.gray600,
    tableBorderSelected: colorPalette.purple400,
    tableBorderHover: colorPalette.purple300,
    tableBorderSeparator: colorPalette.gray400,
    tableRowBackgroundHighlight: colorPalette.purple150,
    tableRowBackgroundHighlightText: colorPalette.gray800,
    tableRowHeaderBackground: colorPalette.gray700,
    tableRowHeaderText: colorPalette.gray150,

    sidebarBackground: colorPalette.gray900,
    sidebarItemBackgroundPending: colorPalette.orange200,
    sidebarItemBackgroundPositive: colorPalette.green400,
    sidebarItemBackgroundFailed: colorPalette.red300,
    sidebarItemAccentSelected: colorPalette.purple200,
    sidebarItemBackgroundHover: colorPalette.gray700,
    sidebarItemText: colorPalette.gray100,
    sidebarItemTextSelected: colorPalette.purple200,

    menuBackground: colorPalette.gray700,
    menuItemBackground: colorPalette.gray200,
    menuItemBackgroundHover: colorPalette.gray500,
    menuItemText: colorPalette.gray100,
    menuItemTextHover: colorPalette.gray50,
    menuItemTextSelected: colorPalette.purple400,
    menuItemTextHeader: colorPalette.purple200,
    menuBorder: colorPalette.gray800,
    menuBorderHover: colorPalette.purple300,
    menuKeybindingText: colorPalette.purple200,
    menuAutoCompleteBackground: colorPalette.gray600,
    menuAutoCompleteBackgroundHover: colorPalette.gray500,
    menuAutoCompleteText: colorPalette.gray100,
    menuAutoCompleteTextHover: colorPalette.green900,
    menuAutoCompleteTextHeader: colorPalette.purple200,
    menuAutoCompleteItemTextHover: colorPalette.gray50,
    menuAutoCompleteItemText: colorPalette.gray100,

    modalBackground: colorPalette.gray700,
    modalBorder: colorPalette.gray200,
    mobileHeaderBackground: colorPalette.gray900,
    mobileHeaderText: colorPalette.purple200,
    mobileHeaderTextSubdued: colorPalette.gray200,
    mobileHeaderTextHover: 'rgba(200, 200, 200, .15)',
    mobilePageBackground: colorPalette.gray900,
    mobileNavBackground: colorPalette.gray600,
    mobileNavItem: colorPalette.gray150,
    mobileNavItemSelected: colorPalette.purple200,
    mobileAccountShadow: colorPalette.gray900,
    mobileAccountText: colorPalette.blue800,
    mobileTransactionSelected: colorPalette.purple300,

    mobileViewTheme: colorPalette.gray900,
    mobileConfigServerViewTheme: colorPalette.purple500,

    markdownNormal: colorPalette.purple700,
    markdownDark: colorPalette.purple500,
    markdownLight: colorPalette.purple800,

    buttonMenuText: colorPalette.gray200,
    buttonMenuTextHover: colorPalette.gray200,
    buttonMenuBackground: colorPalette.gray700,
    buttonMenuBackgroundHover: 'rgba(200, 200, 200, .25)',
    buttonMenuBorder: colorPalette.gray500,
    buttonMenuSelectedText: colorPalette.green800,
    buttonMenuSelectedTextHover: colorPalette.orange800,
    buttonMenuSelectedBackground: colorPalette.orange200,
    buttonMenuSelectedBackgroundHover: colorPalette.gray300,
    buttonMenuSelectedBorder: colorPalette.orange200,

    buttonPrimaryText: colorPalette.white,
    buttonPrimaryTextHover: colorPalette.white,
    buttonPrimaryBackground: colorPalette.purple300,
    buttonPrimaryBackgroundHover: colorPalette.purple300,
    buttonPrimaryBorder: colorPalette.purple300,
    buttonPrimaryShadow: 'rgba(0, 0, 0, 0.6)',
    buttonPrimaryDisabledText: colorPalette.gray400,
    buttonPrimaryDisabledBackground: colorPalette.gray700,

    buttonNormalText: colorPalette.gray150,
    buttonNormalTextHover: colorPalette.gray150,
    buttonNormalBackground: colorPalette.gray600,
    buttonNormalBackgroundHover: colorPalette.gray400,
    buttonNormalBorder: colorPalette.gray300,
    buttonNormalShadow: 'rgba(0, 0, 0, 0.4)',
    buttonNormalDisabledText: colorPalette.gray400,
    buttonNormalDisabledBackground: colorPalette.gray700,

    calendarText: colorPalette.gray50,
    calendarBackground: colorPalette.gray700,
    calendarItemText: colorPalette.gray150,
    calendarItemBackground: colorPalette.gray500,
    calendarSelectedBackground: colorPalette.purple500,

    noticeBackground: colorPalette.green600,
    noticeText: colorPalette.green300,
    warningBackground: colorPalette.orange800,
    warningText: colorPalette.orange200,
    errorBackground: colorPalette.red800,
    errorText: colorPalette.red200,

    floatingActionBarBackground: colorPalette.gray900,
    floatingActionBarBorder: colorPalette.purple300,
    floatingActionBarText: colorPalette.purple200,

    tooltipText: colorPalette.gray100,
    tooltipBackground: colorPalette.gray800,
    tooltipBorder: colorPalette.gray600,
};
