BEGIN TRANSACTION;

ALTER TABLE banks ADD COLUMN website TEXT;
ALTER TABLE banks ADD COLUMN icon TEXT;

ALTER TABLE accounts ADD COLUMN website TEXT;
ALTER TABLE accounts ADD COLUMN icon TEXT;

COMMIT;
