import { t } from 'i18next';

export type Currency = {
  code: string;
  symbol: string;
  name: string;
  decimalPlaces: number;
};

export const currencies: Currency[] = [
  { code: '', name: 'None', symbol: '', decimalPlaces: 2 },
  { code: "AED", name: "UAE Dirham", symbol: "د.إ", decimalPlaces: 2 },
  { code: "AFN", name: "Afghani", symbol: "؋", decimalPlaces: 2 },
  { code: "ALL", name: "Lek", symbol: "L", decimalPlaces: 2 },
  { code: "AMD", name: "Armenian Dram", symbol: "֏", decimalPlaces: 2 },
  { code: "ANG", name: "Netherlands Antillean Guilder", symbol: "ƒ", decimalPlaces: 2 },
  { code: "AOA", name: "Kwanza", symbol: "Kz", decimalPlaces: 2 },
  { code: "ARS", name: "Argentine Peso", symbol: "$", decimalPlaces: 2 },
  { code: "AUD", name: "Australian Dollar", symbol: "A$", decimalPlaces: 2 },
  { code: "AWG", name: "Aruban Florin", symbol: "ƒ", decimalPlaces: 2 },
  { code: "AZN", name: "Azerbaijan Manat", symbol: "₼", decimalPlaces: 2 },
  { code: "BAM", name: "Convertible Mark", symbol: "KM", decimalPlaces: 2 },
  { code: "BBD", name: "Barbados Dollar", symbol: "Bds$", decimalPlaces: 2 },
  { code: "BDT", name: "Taka", symbol: "৳", decimalPlaces: 2 },
  { code: "BGN", name: "Bulgarian Lev", symbol: "лв.", decimalPlaces: 2 },
  { code: "BHD", name: "Bahraini Dinar", symbol: ".د.ب", decimalPlaces: 3 },
  { code: "BIF", name: "Burundi Franc", symbol: "Fr", decimalPlaces: 0 },
  { code: "BMD", name: "Bermudian Dollar", symbol: "BD$", decimalPlaces: 2 },
  { code: "BND", name: "Brunei Dollar", symbol: "B$", decimalPlaces: 2 },
  { code: "BOB", name: "Boliviano", symbol: "Bs.", decimalPlaces: 2 },
  { code: "BRL", name: "Brazilian Real", symbol: "R$", decimalPlaces: 2 },
  { code: "BSD", name: "Bahamian Dollar", symbol: "B$", decimalPlaces: 2 },
  { code: "BTN", name: "Ngultrum", symbol: "Nu.", decimalPlaces: 2 },
  { code: "BWP", name: "Pula", symbol: "P", decimalPlaces: 2 },
  { code: "BYN", name: "Belarusian Ruble", symbol: "Br", decimalPlaces: 2 },
  { code: "BZD", name: "Belize Dollar", symbol: "BZ$", decimalPlaces: 2 },
  { code: "CAD", name: "Canadian Dollar", symbol: "CA$", decimalPlaces: 2 },
  { code: "CDF", name: "Congolese Franc", symbol: "Fr", decimalPlaces: 2 },
  { code: "CHF", name: "Swiss Franc", symbol: "Fr.", decimalPlaces: 2 },
  { code: "CLP", name: "Chilean Peso", symbol: "$", decimalPlaces: 0 },
  { code: "CNY", name: "Yuan Renminbi", symbol: "¥", decimalPlaces: 2 },
  { code: "COP", name: "Colombian Peso", symbol: "$", decimalPlaces: 2 },
  { code: "CRC", name: "Costa Rican Colon", symbol: "₡", decimalPlaces: 2 },
  { code: "CUP", name: "Cuban Peso", symbol: "$", decimalPlaces: 2 },
  { code: "CVE", name: "Cabo Verde Escudo", symbol: "$", decimalPlaces: 2 },
  { code: "CZK", name: "Czech Koruna", symbol: "Kč", decimalPlaces: 2 },
  { code: "DJF", name: "Djibouti Franc", symbol: "Fr", decimalPlaces: 0 },
  { code: "DKK", name: "Danish Krone", symbol: "kr.", decimalPlaces: 2 },
  { code: "DOP", name: "Dominican Peso", symbol: "RD$", decimalPlaces: 2 },
  { code: "DZD", name: "Algerian Dinar", symbol: "د.ج", decimalPlaces: 2 },
  { code: "EGP", name: "Egyptian Pound", symbol: "E£", decimalPlaces: 2 },
  { code: "ERN", name: "Nakfa", symbol: "Nfk", decimalPlaces: 2 },
  { code: "ETB", name: "Ethiopian Birr", symbol: "Br", decimalPlaces: 2 },
  { code: "EUR", name: "Euro", symbol: "€", decimalPlaces: 2 },
  { code: "FJD", name: "Fiji Dollar", symbol: "FJ$", decimalPlaces: 2 },
  { code: "FKP", name: "Falkland Islands Pound", symbol: "£", decimalPlaces: 2 },
  { code: "GBP", name: "Pound Sterling", symbol: "£", decimalPlaces: 2 },
  { code: "GEL", name: "Lari", symbol: "₾", decimalPlaces: 2 },
  { code: "GHS", name: "Ghana Cedi", symbol: "₵", decimalPlaces: 2 },
  { code: "GIP", name: "Gibraltar Pound", symbol: "£", decimalPlaces: 2 },
  { code: "GMD", name: "Dalasi", symbol: "D", decimalPlaces: 2 },
  { code: "GNF", name: "Guinean Franc", symbol: "Fr", decimalPlaces: 0 },
  { code: "GTQ", name: "Quetzal", symbol: "Q", decimalPlaces: 2 },
  { code: "GYD", name: "Guyana Dollar", symbol: "G$", decimalPlaces: 2 },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$", decimalPlaces: 2 },
  { code: "HNL", name: "Lempira", symbol: "L", decimalPlaces: 2 },
  { code: "HRK", name: "Kuna", symbol: "kn", decimalPlaces: 2 },
  { code: "HTG", name: "Gourde", symbol: "G", decimalPlaces: 2 },
  { code: "HUF", name: "Forint", symbol: "Ft", decimalPlaces: 2 },
  { code: "IDR", name: "Rupiah", symbol: "Rp", decimalPlaces: 2 },
  { code: "ILS", name: "New Israeli Sheqel", symbol: "₪", decimalPlaces: 2 },
  { code: "INR", name: "Indian Rupee", symbol: "₹", decimalPlaces: 2 },
  { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د", decimalPlaces: 3 },
  { code: "IRR", name: "Iranian Rial", symbol: "﷼", decimalPlaces: 2 },
  { code: "ISK", name: "Iceland Krona", symbol: "kr", decimalPlaces: 0 },
  { code: "JMD", name: "Jamaican Dollar", symbol: "J$", decimalPlaces: 2 },
  { code: "JOD", name: "Jordanian Dinar", symbol: "د.ا", decimalPlaces: 3 },
  { code: "JPY", name: "Yen", symbol: "¥", decimalPlaces: 0 },
  { code: "KES", name: "Kenyan Shilling", symbol: "Sh", decimalPlaces: 2 },
  { code: "KGS", name: "Som", symbol: "с", decimalPlaces: 2 },
  { code: "KHR", name: "Riel", symbol: "៛", decimalPlaces: 2 },
  { code: "KMF", name: "Comorian Franc", symbol: "Fr", decimalPlaces: 0 },
  { code: "KPW", name: "North Korean Won", symbol: "₩", decimalPlaces: 2 },
  { code: "KRW", name: "Won", symbol: "₩", decimalPlaces: 0 },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك", decimalPlaces: 3 },
  { code: "KYD", name: "Cayman Islands Dollar", symbol: "CI$", decimalPlaces: 2 },
  { code: "KZT", name: "Tenge", symbol: "₸", decimalPlaces: 2 },
  { code: "LAK", name: "Lao Kip", symbol: "₭", decimalPlaces: 2 },
  { code: "LBP", name: "Lebanese Pound", symbol: "ل.ل", decimalPlaces: 2 },
  { code: "LKR", name: "Sri Lanka Rupee", symbol: "Rs", decimalPlaces: 2 },
  { code: "LRD", name: "Liberian Dollar", symbol: "L$", decimalPlaces: 2 },
  { code: "LSL", name: "Loti", symbol: "L", decimalPlaces: 2 },
  { code: "LYD", name: "Libyan Dinar", symbol: "ل.د", decimalPlaces: 3 },
  { code: "MAD", name: "Moroccan Dirham", symbol: "د.م.", decimalPlaces: 2 },
  { code: "MDL", name: "Moldovan Leu", symbol: "L", decimalPlaces: 2 },
  { code: "MGA", name: "Malagasy Ariary", symbol: "Ar", decimalPlaces: 2 },
  { code: "MKD", name: "Denar", symbol: "ден", decimalPlaces: 2 },
  { code: "MMK", name: "Kyat", symbol: "Ks", decimalPlaces: 2 },
  { code: "MNT", name: "Tugrik", symbol: "₮", decimalPlaces: 2 },
  { code: "MOP", name: "Pataca", symbol: "MOP$", decimalPlaces: 2 },
  { code: "MRU", name: "Ouguiya", symbol: "UM", decimalPlaces: 2 },
  { code: "MUR", name: "Mauritius Rupee", symbol: "₨", decimalPlaces: 2 },
  { code: "MVR", name: "Rufiyaa", symbol: ".ރ", decimalPlaces: 2 },
  { code: "MWK", name: "Malawi Kwacha", symbol: "MK", decimalPlaces: 2 },
  { code: "MXN", name: "Mexican Peso", symbol: "MX$", decimalPlaces: 2 },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM", decimalPlaces: 2 },
  { code: "MZN", name: "Mozambique Metical", symbol: "MT", decimalPlaces: 2 },
  { code: "NAD", name: "Namibia Dollar", symbol: "N$", decimalPlaces: 2 },
  { code: "NGN", name: "Naira", symbol: "₦", decimalPlaces: 2 },
  { code: "NIO", name: "Cordoba Oro", symbol: "C$", decimalPlaces: 2 },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr", decimalPlaces: 2 },
  { code: "NPR", name: "Nepalese Rupee", symbol: "रू", decimalPlaces: 2 },
  { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$", decimalPlaces: 2 },
  { code: "OMR", name: "Rial Omani", symbol: "ر.ع.", decimalPlaces: 3 },
  { code: "PAB", name: "Balboa", symbol: "B/.", decimalPlaces: 2 },
  { code: "PEN", name: "Sol", symbol: "S/.", decimalPlaces: 2 },
  { code: "PGK", name: "Kina", symbol: "K", decimalPlaces: 2 },
  { code: "PHP", name: "Philippine Peso", symbol: "₱", decimalPlaces: 2 },
  { code: "PKR", name: "Pakistan Rupee", symbol: "₨", decimalPlaces: 2 },
  { code: "PLN", name: "Zloty", symbol: "zł", decimalPlaces: 2 },
  { code: "PYG", name: "Guarani", symbol: "₲", decimalPlaces: 0 },
  { code: "QAR", name: "Qatari Rial", symbol: "ر.ق", decimalPlaces: 2 },
  { code: "RON", name: "Romanian Leu", symbol: "lei", decimalPlaces: 2 },
  { code: "RSD", name: "Serbian Dinar", symbol: "дин.", decimalPlaces: 2 },
  { code: "RUB", name: "Russian Ruble", symbol: "₽", decimalPlaces: 2 },
  { code: "RWF", name: "Rwanda Franc", symbol: "Fr", decimalPlaces: 0 },
  { code: "SAR", name: "Saudi Riyal", symbol: "﷼", decimalPlaces: 2 },
  { code: "SBD", name: "Solomon Islands Dollar", symbol: "SI$", decimalPlaces: 2 },
  { code: "SCR", name: "Seychelles Rupee", symbol: "₨", decimalPlaces: 2 },
  { code: "SDG", name: "Sudanese Pound", symbol: "ج.س.", decimalPlaces: 2 },
  { code: "SEK", name: "Swedish Krona", symbol: "kr", decimalPlaces: 2 },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$", decimalPlaces: 2 },
  { code: "SHP", name: "Saint Helena Pound", symbol: "£", decimalPlaces: 2 },
  { code: "SLL", name: "Leone", symbol: "Le", decimalPlaces: 2 },
  { code: "SOS", name: "Somali Shilling", symbol: "Sh", decimalPlaces: 2 },
  { code: "SRD", name: "Surinam Dollar", symbol: "$", decimalPlaces: 2 },
  { code: "SSP", name: "South Sudanese Pound", symbol: "£", decimalPlaces: 2 },
  { code: "STN", name: "Dobra", symbol: "Db", decimalPlaces: 2 },
  { code: "SYP", name: "Syrian Pound", symbol: "£", decimalPlaces: 2 },
  { code: "SZL", name: "Lilangeni", symbol: "L", decimalPlaces: 2 },
  { code: "THB", name: "Baht", symbol: "฿", decimalPlaces: 2 },
  { code: "TJS", name: "Somoni", symbol: "с.", decimalPlaces: 2 },
  { code: "TMT", name: "Turkmenistan New Manat", symbol: "m.", decimalPlaces: 2 },
  { code: "TND", name: "Tunisian Dinar", symbol: "د.ت", decimalPlaces: 3 },
  { code: "TOP", name: "Pa’anga", symbol: "T$", decimalPlaces: 2 },
  { code: "TRY", name: "Turkish Lira", symbol: "₺", decimalPlaces: 2 },
  { code: "TTD", name: "Trinidad and Tobago Dollar", symbol: "TT$", decimalPlaces: 2 },
  { code: "TWD", name: "New Taiwan Dollar", symbol: "NT$", decimalPlaces: 2 },
  { code: "TZS", name: "Tanzanian Shilling", symbol: "Sh", decimalPlaces: 2 },
  { code: "UAH", name: "Hryvnia", symbol: "₴", decimalPlaces: 2 },
  { code: "UGX", name: "Uganda Shilling", symbol: "Sh", decimalPlaces: 0 },
  { code: "USD", name: "US Dollar", symbol: "$", decimalPlaces: 2 },
  { code: "UYU", name: "Peso Uruguayo", symbol: "$U", decimalPlaces: 2 },
  { code: "UZS", name: "Uzbekistan Sum", symbol: "Sʻ", decimalPlaces: 2 },
  { code: "VES", name: "Bolívar Soberano", symbol: "Bs.", decimalPlaces: 2 },
  { code: "VND", name: "Dong", symbol: "₫", decimalPlaces: 0 },
  { code: "VUV", name: "Vatu", symbol: "Vt", decimalPlaces: 0 },
  { code: "WST", name: "Tala", symbol: "T", decimalPlaces: 2 },
  { code: "XAF", name: "CFA Franc BEAC", symbol: "Fr", decimalPlaces: 0 },
  { code: "XCD", name: "East Caribbean Dollar", symbol: "$", decimalPlaces: 2 },
  { code: "XOF", name: "CFA Franc BCEAO", symbol: "Fr", decimalPlaces: 0 },
  { code: "XPF", name: "CFP Franc", symbol: "₣", decimalPlaces: 0 },
  { code: "YER", name: "Yemeni Rial", symbol: "﷼", decimalPlaces: 2 },
  { code: "ZAR", name: "Rand", symbol: "R", decimalPlaces: 2 },
  { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK", decimalPlaces: 2 },
  { code: "ZWL", name: "Zimbabwe Dollar", symbol: "$", decimalPlaces: 2 },
];

export function getCurrency(code: string): Currency {
  return currencies.find(c => c.code === code) || currencies[0];
}

export function getLocalizedCurrencyOption(currency: Currency): [string, string] {
  if (currency.code === '') {
    return [currency.code, t('None')];
  }
  return [currency.code, `${currency.code} - ${currency.name} (${currency.symbol})`];
}