import { type NumberFormats } from './util';

export type Currency = {
  code: string;
  symbol: string;
  name: string;
  decimalPlaces: number;
  numberFormat: NumberFormats;
  symbolFirst: boolean;
};

// When adding a new currency with a higher decimal precision, make sure to update
// the MAX_SAFE_NUMBER in util.ts.
// Number formats and symbol placement based on CLDR (Common Locale Data Repository) /
// LDML (Locale Data Markup Language) locale conventions and Intl.NumberFormat standards
// References:
// - https://www.localeplanet.com/icu/decimal-symbols.html
// - https://www.localeplanet.com/api/auto/currencymap.html
// - https://openexchangerates.org/api/currencies.json
//
// Currencies marked with "deprecated" comments are due to be removed in a forthcoming
// update to openexchangerates as they are no longer supported and/or have been replaced.
//
// prettier-ignore
export const currencies: Currency[] = [
  { code: '', name: 'None', symbol: '', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ.‏', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'AFN', name: 'Afghan Afghani', symbol: '؋', decimalPlaces: 0, numberFormat: 'comma-dot', symbolFirst: false },
  { code: 'ALL', name: 'Albanian Lek', symbol: 'Lekë', decimalPlaces: 0, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'AMD', name: 'Armenian Dram', symbol: '֏', decimalPlaces: 0, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'NAf.', decimalPlaces: 2, numberFormat: 'dot-comma', symbolFirst: true }, // deprecated
  { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz', decimalPlaces: 2, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'ARS', name: 'Argentine Peso', symbol: 'Arg$', decimalPlaces: 2, numberFormat: 'dot-comma', symbolFirst: true },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'AWG', name: 'Aruban Florin', symbol: 'Afl.', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', decimalPlaces: 2, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'КМ', decimalPlaces: 2, numberFormat: 'dot-comma', symbolFirst: false },
  { code: 'BBD', name: 'Barbadian Dollar', symbol: 'Bds$', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв.', decimalPlaces: 2, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: 'د.ب.‏', decimalPlaces: 3, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'BIF', name: 'Burundian Franc', symbol: 'FBu', decimalPlaces: 0, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'BMD', name: 'Bermudan Dollar', symbol: 'BD$', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'BND', name: 'Brunei Dollar', symbol: 'B$', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs', decimalPlaces: 2, numberFormat: 'dot-comma', symbolFirst: true },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', decimalPlaces: 2, numberFormat: 'dot-comma', symbolFirst: true },
  { code: 'BSD', name: 'Bahamian Dollar', symbol: 'B$', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'BTC', name: 'Bitcoin', symbol: '₿', decimalPlaces: 8, numberFormat: 'sat-comma', symbolFirst: false },
  { code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu.', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'BWP', name: 'Botswanan Pula', symbol: 'P', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br', decimalPlaces: 2, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'BZD', name: 'Belize Dollar', symbol: 'BZ$', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'CA$', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'CDF', name: 'Congolese Franc', symbol: 'FC', decimalPlaces: 2, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', decimalPlaces: 2, numberFormat: 'apostrophe-dot', symbolFirst: true },
  { code: 'CLF', name: 'Chilean Unit of Account (UF)', symbol: 'UF', decimalPlaces: 4, numberFormat: 'dot-comma', symbolFirst: true },
  { code: 'CLP', name: 'Chilean Peso', symbol: 'CL$', decimalPlaces: 0, numberFormat: 'dot-comma', symbolFirst: true },
  { code: 'CNH', name: 'Chinese Yuan (Offshore)', symbol: 'CN¥', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'CNY', name: 'Yuan Renminbi', symbol: '¥', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'COP', name: 'Colombian Peso', symbol: 'Col$', decimalPlaces: 2, numberFormat: 'dot-comma', symbolFirst: true },
  { code: 'CRC', name: 'Costa Rican Colón', symbol: '₡', decimalPlaces: 2, numberFormat: 'space-comma', symbolFirst: true },
  { code: 'CUC', name: 'Cuban Convertible Peso', symbol: 'CUC$', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'CUP', name: 'Cuban Peso', symbol: 'CU$', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'CVE', name: 'Cape Verdean Escudo', symbol: 'Esc', decimalPlaces: 2, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', decimalPlaces: 2, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj', decimalPlaces: 0, numberFormat: 'comma-dot', symbolFirst: false },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr', decimalPlaces: 2, numberFormat: 'dot-comma', symbolFirst: false },
  { code: 'DOP', name: 'Dominican Peso', symbol: 'RD$', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'DZD', name: 'Algerian Dinar', symbol: 'د.ج.‏', decimalPlaces: 2, numberFormat: 'dot-comma', symbolFirst: false },
  { code: 'EGP', name: 'Egyptian Pound', symbol: 'ج.م.‏', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'ETB', name: 'Ethiopian Birr', symbol: 'ብር', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'EUR', name: 'Euro', symbol: '€', decimalPlaces: 2, numberFormat: 'dot-comma', symbolFirst: false },
  { code: 'FJD', name: 'Fijian Dollar', symbol: 'FJ$', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'FKP', name: 'Falkland Islands Pound', symbol: 'FK£', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'GBP', name: 'Pound Sterling', symbol: '£', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'GEL', name: 'Georgian Lari', symbol: '₾', decimalPlaces: 2, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'GGP', name: 'Guernsey Pound', symbol: 'GG£', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: 'GH₵', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'GIP', name: 'Gibraltar Pound', symbol: 'GI£', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'GMD', name: 'Gambian Dalasi', symbol: 'D', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'GNF', name: 'Guinean Franc', symbol: 'FG', decimalPlaces: 0, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'GYD', name: 'Guyanaese Dollar', symbol: 'GY$', decimalPlaces: 0, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'HNL', name: 'Honduran Lempira', symbol: 'L', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'HRK', name: 'Croatian Kuna', symbol: 'HRK', decimalPlaces: 2, numberFormat: 'dot-comma', symbolFirst: false },
  { code: 'HTG', name: 'Haitian Gourde', symbol: 'G', decimalPlaces: 2, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', decimalPlaces: 2, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', decimalPlaces: 2, numberFormat: 'dot-comma', symbolFirst: true },
  { code: 'ILS', name: 'Israeli New Shekel', symbol: '₪', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'IMP', name: 'Manx Pound', symbol: 'IM£', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', decimalPlaces: 2, numberFormat: 'comma-dot-in', symbolFirst: true },
  { code: 'IQD', name: 'Iraqi Dinar', symbol: 'د.ع.‏', decimalPlaces: 0, numberFormat: 'comma-dot', symbolFirst: false },
  { code: 'IRR', name: 'Iranian Rial', symbol: 'IRR', decimalPlaces: 0, numberFormat: 'comma-dot', symbolFirst: false },
  { code: 'ISK', name: 'Icelandic Króna', symbol: 'ISK', decimalPlaces: 0, numberFormat: 'dot-comma', symbolFirst: false },
  { code: 'JEP', name: 'Jersey Pound', symbol: 'JE£', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'JMD', name: 'Jamaican Dollar', symbol: 'J$', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'JOD', name: 'Jordanian Dinar', symbol: 'د.أ.‏', decimalPlaces: 3, numberFormat: 'comma-dot', symbolFirst: false },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', decimalPlaces: 0, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'Ksh', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'KGS', name: 'Kyrgystani Som', symbol: 'сом', decimalPlaces: 2, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'KHR', name: 'Cambodian Riel', symbol: '៛', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'KMF', name: 'Comorian Franc', symbol: 'CF', decimalPlaces: 0, numberFormat: 'comma-dot', symbolFirst: false },
  { code: 'KPW', name: 'North Korean Won', symbol: 'KPW', decimalPlaces: 0, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩', decimalPlaces: 0, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك.‏', decimalPlaces: 3, numberFormat: 'comma-dot', symbolFirst: false },
  { code: 'KYD', name: 'Cayman Islands Dollar', symbol: 'CI$', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', decimalPlaces: 2, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'LAK', name: 'Laotian Kip', symbol: '₭', decimalPlaces: 0, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'LBP', name: 'Lebanese Pound', symbol: 'ل.ل.‏', decimalPlaces: 0, numberFormat: 'comma-dot', symbolFirst: false },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'රු.', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'LRD', name: 'Liberian Dollar', symbol: 'L$', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'LSL', name: 'Lesotho Loti', symbol: 'LSL', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'LYD', name: 'Libyan Dinar', symbol: 'د.ل.‏', decimalPlaces: 3, numberFormat: 'dot-comma', symbolFirst: false },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: 'د.م.‏', decimalPlaces: 2, numberFormat: 'dot-comma', symbolFirst: false },
  { code: 'MDL', name: 'Moldovan Leu', symbol: 'L', decimalPlaces: 2, numberFormat: 'dot-comma', symbolFirst: false },
  { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar', decimalPlaces: 0, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'MKD', name: 'Macedonian Denar', symbol: 'ден', decimalPlaces: 2, numberFormat: 'dot-comma', symbolFirst: false },
  { code: 'MMK', name: 'Myanmar Kyat', symbol: 'K', decimalPlaces: 0, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮', decimalPlaces: 0, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'MOP', name: 'Macanese Pataca', symbol: 'MOP$', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'UM', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: false },
  { code: 'MUR', name: 'Mauritian Rupee', symbol: 'Rs', decimalPlaces: 0, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'ރ.', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: false },
  { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'MXN', name: 'Mexican Peso', symbol: 'MX$', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'MZN', name: 'Mozambican Metical', symbol: 'MTn', decimalPlaces: 2, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'NAD', name: 'Namibian Dollar', symbol: 'N$', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C$', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', decimalPlaces: 2, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'NPR', name: 'Nepalese Rupee', symbol: 'नेरू', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'OMR', name: 'Omani Rial', symbol: 'ر.ع.‏', decimalPlaces: 3, numberFormat: 'comma-dot', symbolFirst: false },
  { code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: 'Rs', decimalPlaces: 0, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'PLN', name: 'Polish Złoty', symbol: 'zł', decimalPlaces: 2, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'PYG', name: 'Paraguayan Guarani', symbol: 'Gs.', decimalPlaces: 0, numberFormat: 'dot-comma', symbolFirst: true },
  { code: 'QAR', name: 'Qatari Riyal', symbol: 'ر.ق.‏', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'RON', name: 'Romanian Leu', symbol: 'lei', decimalPlaces: 2, numberFormat: 'dot-comma', symbolFirst: false },
  { code: 'RSD', name: 'Serbian Dinar', symbol: 'дин', decimalPlaces: 2, numberFormat: 'dot-comma', symbolFirst: false },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽', decimalPlaces: 2, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'RWF', name: 'Rwandan Franc', symbol: 'RF', decimalPlaces: 0, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'SAR', name: 'Saudi Riyal', symbol: 'ر.س.‏', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'SBD', name: 'Solomon Islands Dollar', symbol: 'SI$', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'SCR', name: 'Seychellois Rupee', symbol: 'SR', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'SDG', name: 'Sudanese Pound', symbol: 'ج.س.', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: false },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', decimalPlaces: 2, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'SHP', name: 'Saint Helena Pound', symbol: 'SH£', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'SLE', name: 'Sierra Leonean Leone', symbol: 'Le', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'SLL', name: 'Sierra Leonean Leone (Old)', symbol: 'Le', decimalPlaces: 0, numberFormat: 'comma-dot', symbolFirst: true }, // deprecated: replaced by SLE
  { code: 'SOS', name: 'Somali Shilling', symbol: 'Sh.So.', decimalPlaces: 0, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'SRD', name: 'Surinamese Dollar', symbol: 'Sr$', decimalPlaces: 2, numberFormat: 'dot-comma', symbolFirst: true },
  { code: 'SSP', name: 'South Sudanese Pound', symbol: 'SS£', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'STD', name: 'São Tomé and Príncipe Dobra (pre-2018)', symbol: 'Db', decimalPlaces: 0, numberFormat: 'space-comma', symbolFirst: false }, // deprecated: replaced by STN
  { code: 'STN', name: 'São Tomé and Príncipe Dobra', symbol: 'STN', decimalPlaces: 2, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'SVC', name: 'Salvadoran Colón', symbol: '₡', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'SYP', name: 'Syrian Pound', symbol: 'ل.س.‏', decimalPlaces: 0, numberFormat: 'comma-dot', symbolFirst: false },
  { code: 'SZL', name: 'Swazi Lilangeni', symbol: 'E', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'THB', name: 'Thai Baht', symbol: '฿', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'сом.', decimalPlaces: 2, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'TMT', name: 'Turkmenistani Manat', symbol: 'm', decimalPlaces: 2, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'TND', name: 'Tunisian Dinar', symbol: 'د.ت.‏', decimalPlaces: 3, numberFormat: 'dot-comma', symbolFirst: false },
  { code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T$', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺', decimalPlaces: 2, numberFormat: 'dot-comma', symbolFirst: true },
  { code: 'TTD', name: 'Trinidad and Tobago Dollar', symbol: 'TT$', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT$', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh', decimalPlaces: 0, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', decimalPlaces: 2, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh', decimalPlaces: 0, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'USD', name: 'US Dollar', symbol: '$', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'UYU', name: 'Uruguayan Peso', symbol: '$U', decimalPlaces: 2, numberFormat: 'dot-comma', symbolFirst: true },
  { code: 'UZS', name: 'Uzbekistan Som', symbol: 'сўм', decimalPlaces: 0, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'VEF', name: 'Venezuelan Bolívar Fuerte (Old)', symbol: 'Bs.F', decimalPlaces: 2, numberFormat: 'dot-comma', symbolFirst: true }, // deprecated: replaced by VES
  { code: 'VES', name: 'Venezuelan Bolívar Soberano', symbol: 'Bs.S', decimalPlaces: 2, numberFormat: 'dot-comma', symbolFirst: true },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', decimalPlaces: 0, numberFormat: 'dot-comma', symbolFirst: false },
  { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VT', decimalPlaces: 0, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'WST', name: 'Samoan Tala', symbol: 'WS$', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'XAF', name: 'CFA Franc BEAC', symbol: 'FCFA', decimalPlaces: 0, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'XAG', name: 'Silver Ounce', symbol: 'oz t', decimalPlaces: 4, numberFormat: 'comma-dot', symbolFirst: false },
  { code: 'XAU', name: 'Gold Ounce', symbol: 'oz t', decimalPlaces: 4, numberFormat: 'comma-dot', symbolFirst: false },
  { code: 'XCD', name: 'East Caribbean Dollar', symbol: 'EC$', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'XCG', name: 'Caribbean Guilder', symbol: 'ƒ', decimalPlaces: 2, numberFormat: 'dot-comma', symbolFirst: true },
  { code: 'XDR', name: 'Special Drawing Rights', symbol: 'XDR', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'XOF', name: 'CFA Franc BCEAO', symbol: 'CFA', decimalPlaces: 0, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'XPD', name: 'Palladium Ounce', symbol: 'oz t', decimalPlaces: 4, numberFormat: 'comma-dot', symbolFirst: false },
  { code: 'XPF', name: 'CFP Franc', symbol: 'FCFP', decimalPlaces: 0, numberFormat: 'space-comma', symbolFirst: false },
  { code: 'XPT', name: 'Platinum Ounce', symbol: 'oz t', decimalPlaces: 4, numberFormat: 'comma-dot', symbolFirst: false },
  { code: 'YER', name: 'Yemeni Rial', symbol: 'ر.ي.‏', decimalPlaces: 0, numberFormat: 'comma-dot', symbolFirst: false },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R', decimalPlaces: 2, numberFormat: 'space-comma', symbolFirst: true },
  { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'K', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'ZWG', name: 'Zimbabwean ZiG', symbol: 'ZiG', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true },
  { code: 'ZWL', name: 'Zimbabwean Dollar', symbol: 'Z$', decimalPlaces: 2, numberFormat: 'comma-dot', symbolFirst: true }, // deprecated: replaced by ZWG
];

export function getCurrency(code: string): Currency {
  return currencies.find(c => c.code === code) || currencies[0];
}
