name: Check release notes

on:
  pull_request:
    branches: '*'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Generate release notes
        uses: actualbudget/actions/release-notes/check@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
