name: Build Nightly Docker Image

# Nightly Docker images are built for every push to master
on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: docker-nightly-build
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    if: github.event_name == 'workflow_dispatch' || !github.event.repository.fork
    name: Build Docker image
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      packages: write # push images to ghcr.io
    strategy:
      matrix:
        os: [ubuntu, alpine]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Build and push
        uses: ./.github/actions/docker-build-and-push
        with:
          # Creates the following tags:
          # - actual-server:nightly
          # - actual-server:edge (kept for backwards compatibility)
          tags: |
            type=raw,value=nightly,enable={{is_default_branch}}
            type=raw,value=edge,enable={{is_default_branch}}
            type=sha
          images: |
            ${{ !github.event.repository.fork && 'actualbudget/actual-server' || '' }}
            ghcr.io/${{ github.repository_owner }}/actual-server
            ghcr.io/${{ github.repository_owner }}/actual
          os: ${{ matrix.os }}
          dockerhub-username: ${{ !github.event.repository.fork && secrets.DOCKERHUB_USERNAME || '' }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
