name: Generate Release Notes

on:
  push:
    branches:
      - '*'
      # - release/*

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate release notes
        uses: actualbudget/actions/release-notes/generate@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
