name: Mark new issue for triage

on:
  issues:
    types: [opened]

jobs:
  needs-triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        if: github.event.issue.labels == null
        with:
          labels: needs triage
