name: Import secrets and variables to Depot CI
on: push

permissions:
  id-token: write
  contents: read

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: depot/setup-action@v1
      - name: Import secrets
        env:
          ACTIONS_UPDATE_TOKEN: ${{ secrets.ACTIONS_UPDATE_TOKEN }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
        run: |
          unset DEPOT_TOKEN
          depot ci secrets add ACTIONS_UPDATE_TOKEN="$ACTIONS_UPDATE_TOKEN" CSC_KEY_PASSWORD="$CSC_KEY_PASSWORD" CSC_LINK="$CSC_LINK" --repo actualbudget/actual
