name: Add Label
on:
  pull_request:
    types:
      - opened

jobs:
  add-label:
    name: Add Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: christianvuerings/add-labels@v1
        with:
          labels: |
            waiting-review            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
