name: Mark new issue for triage

on:
  pull_request:
    types: [opened]

jobs:
  pr-waiting-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: waiting-review
