name: Mark new pull request as waiting review

on:
  pull_request:
    types: [opened]

jobs:
  needs-triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: waiting-review
