name: Disabled - Add WIP prefix to PRs (replaced by existing workflow)

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Disabled; functionality handled in existing workflow."

