name: Publish npm packages

# Npm packages are published for every new tag and nightly schedule
on:
  push:
    tags:
      - 'v*.*.*'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-and-pack:
    runs-on: ubuntu-latest
    name: Build and pack npm packages
    if: github.event_name == 'push' || (github.event.repository.fork == false)
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Update package versions
        if: github.event_name != 'push'
        run: |
          # Get new nightly versions
          NEW_CORE_VERSION=$(yarn workspace @actual-app/ci-actions tsx bin/get-next-package-version.ts --package-json ./packages/loot-core/package.json --type nightly)
          NEW_WEB_VERSION=$(yarn workspace @actual-app/ci-actions tsx bin/get-next-package-version.ts --package-json ./packages/desktop-client/package.json --type nightly)
          NEW_SYNC_VERSION=$(yarn workspace @actual-app/ci-actions tsx bin/get-next-package-version.ts --package-json ./packages/sync-server/package.json --type nightly)
          NEW_API_VERSION=$(yarn workspace @actual-app/ci-actions tsx bin/get-next-package-version.ts --package-json ./packages/api/package.json --type nightly)
          NEW_CLI_VERSION=$(yarn workspace @actual-app/ci-actions tsx bin/get-next-package-version.ts --package-json ./packages/cli/package.json --type nightly)

          # Set package versions
          npm version $NEW_CORE_VERSION --no-git-tag-version --workspace=@actual-app/core --no-workspaces-update
          npm version $NEW_WEB_VERSION --no-git-tag-version --workspace=@actual-app/web --no-workspaces-update
          npm version $NEW_SYNC_VERSION --no-git-tag-version --workspace=@actual-app/sync-server --no-workspaces-update
          npm version $NEW_API_VERSION --no-git-tag-version --workspace=@actual-app/api --no-workspaces-update
          npm version $NEW_CLI_VERSION --no-git-tag-version --workspace=@actual-app/cli --no-workspaces-update

      - name: Yarn install
        if: github.event_name != 'push'
        run: |
          # Required after nightly `npm version` updates workspace manifests.
          yarn install

      - name: Pack the core package
        run: |
          yarn workspace @actual-app/core pack --filename @actual-app/core.tgz

      - name: Build Server & Web
        run: yarn build:server

      - name: Pack the web and server packages
        run: |
          yarn workspace @actual-app/web pack --filename @actual-app/web.tgz
          yarn workspace @actual-app/sync-server pack --filename @actual-app/sync-server.tgz

      - name: Build API
        run: yarn build:api

      - name: Pack the api package
        run: |
          yarn workspace @actual-app/api pack --filename @actual-app/api.tgz

      - name: Build CLI
        run: yarn workspace @actual-app/cli build

      - name: Pack the cli package
        run: |
          yarn workspace @actual-app/cli pack --filename @actual-app/cli.tgz

      - name: Upload package artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: ${{ !env.ACT }}
        with:
          name: npm-packages
          path: |
            packages/loot-core/@actual-app/core.tgz
            packages/desktop-client/@actual-app/web.tgz
            packages/sync-server/@actual-app/sync-server.tgz
            packages/api/@actual-app/api.tgz
            packages/cli/@actual-app/cli.tgz

  publish:
    runs-on: ubuntu-latest
    name: Publish npm packages
    needs: build-and-pack
    environment: release
    permissions:
      contents: read
      packages: write
      id-token: write # Required for OIDC
    env:
      NPM_DIST_TAG: ${{ github.event_name != 'push' && 'nightly' || '' }}
    steps:
      - name: Download the artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: npm-packages

      - name: Setup node and npm registry
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
          check-latest: true
          registry-url: 'https://registry.npmjs.org'

      - name: Publish Core
        run: |
          npm publish loot-core/@actual-app/core.tgz --access public ${NPM_DIST_TAG:+--tag "$NPM_DIST_TAG"}

      - name: Publish Web
        run: |
          npm publish desktop-client/@actual-app/web.tgz --access public ${NPM_DIST_TAG:+--tag "$NPM_DIST_TAG"}

      - name: Publish Sync-Server
        run: |
          npm publish sync-server/@actual-app/sync-server.tgz --access public ${NPM_DIST_TAG:+--tag "$NPM_DIST_TAG"}

      - name: Publish API
        run: |
          npm publish api/@actual-app/api.tgz --access public ${NPM_DIST_TAG:+--tag "$NPM_DIST_TAG"}

      - name: Publish CLI
        run: |
          npm publish cli/@actual-app/cli.tgz --access public ${NPM_DIST_TAG:+--tag "$NPM_DIST_TAG"}
