name: Mark PR As Stale
on:
  schedule:
    - cron: "30 1 * * *"
jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v7
        with:
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          stale-pr-message: "🚧🚨 This Pull Request is being marked as stale due to 30 days of inactivity. 🚧🚨"
          days-before-pr-stale: 30
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
