name: Add WIP

on:
  pull_request:
    types:
      - opened

jobs:
  add_wip_prefix:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name : Add WIP
      env:
          TITLE: ${{ github.event.pull_request.title }}
      with:
        pr_title: echo [WIP] $TITLE
